config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  resources :users, :only => [:new, :create, :index]
  resources :projects
  resources :designers
  resources :clients
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :projects
    belongs_to :designer, :optional => true
end

app/models/designer.rb
class Designer < ApplicationRecord
    has_many :projects
    has_many :clients
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :designer, :optional => true
    belongs_to :client, :optional => true
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, :presence => true
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :fetch_user

    private 
    def fetch_user
        @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
        session[:user_id] =nil unless @current_user.present?
    end

    def check_for_login
        redirect_to login_path unless @current_user.present?
    end

    def check_for_admin
        redirect_to login_path unless (@current_user.present? && @current_user.admin?)
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :check_for_login

  def index
    @clients = Client.all
  end

  def new
    @client = Client.new

  end

  def create
    client = Client.create client_params
    redirect_to client
  end

  def edit
    @client = Client.find params[:id]
  end

  def update
    client = Client.find params[:id]
    client.update client_params
    redirect_to client
  end

  def show
    @client = Client.find params[:id]
  end

  def destroy
    client = Client.find params[:id]
    client.destroy
    redirect_to clients_path
  end

  private
  def client_params 
    params.require(:client).permit(:name, :phone, :email, :address, :heard_us_from, :preferred_style, :image)
  end
end

app/controllers/designers_controller.rb
class DesignersController < ApplicationController
  before_action :check_for_login

  def index
    @designers = Designer.all
  end

  def new
    @designer = Designer.new

  end

  def create
    designer = Designer.create designer_params
    @current_user.designer << designer
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      designer.image = req["public_id"]
      designer.save
    end

    redirect_to root_path
  end

  def edit
    @designer = Designer.find params[:id]
  end

  def update
    designer = Designer.find params[:id]
    designer.update designer_params
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      designer.image = req["public_id"]
      designer.save
    end
    redirect_to designer
  end

  def show
    @designer = Designer.find params[:id]
  end

  def destroy
    designer = Designer.find params[:id]
    designer.destroy
    redirect_to designers_path
  end

  private
  def designer_params 
    params.require(:designer).permit(:name, :hireyear, :dob, :email, :phone, :address, :award)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :check_for_login

  def index
    @projects = Project.all
  end

  def new
      @project = Project.new

  end

  def create
    project = Project.create project_params
    redirect_to project
  end

  def edit
    @project = Project.find params[:id]
  end

  def update
    project = Project.find params[:id]
    project.update project_params
    redirect_to project
  end

  def show
    @project = Project.find params[:id]
  end

  def destroy
    project = Project.find params[:id]
    project.destroy
    redirect_to projects_path
  end

  private
  def project_params
    params.require(:project).permit(:name, :location, :area, :style, :start_date, :finished, :estimate_time_finish, :image, :cost, :designer_id, :client_id)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id   
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, :only => [:index]

  def index
    @users = User.all
  end

  def new
    @user =User.new
  end

  def create 
    @user =User.new user_params  
    if @user.save
      session[:user_id] = @user.id
      redirect_to designers_path
    else
      render :new  
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/designers_helper.rb
module DesignersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clients/_form.html.erb
<%= form_for @client do |f| %>
    <%= f.label :name, :class=>'form-control-plaintext' %>
    <%= f.text_field :name, :class => 'form-control'%>
    <%= f.label :phone, :class=>'form-control-plaintext'%>
    <%= f.text_field :phone, :class => 'form-control'%>
    <%= f.label :email, :class=>'form-control-plaintext'%>
    <%= f.text_field :email, :class => 'form-control'%>
    <%= f.label :address, :class=>'form-control-plaintext'%>
    <%= f.text_field :address, :class => 'form-control'%>
    <%= f.label :heard_us_from, 'Heard us from', :class=>'form-control-plaintext'%>
    <%= f.text_field :heard_us_from, :class => 'form-control' %>
    <%= f.label :preferred_style, 'Preferred Style', :class=>'form-control-plaintext' %>
    <%= f.text_field :preferred_style, :class => 'form-control' %>
    <%= f.label :image, :class=>'form-control-plaintext'%>
    <%= f.text_field :image, :class => 'form-control'%><br>

    <%= f.submit%>
<% end %>

app/views/clients/edit.html.erb
<div class="container-sm">
    <h1>Edit Client</h1>

    <%= render :partial => 'form' %>
</div>

app/views/clients/index.html.erb
<div class="container">
    <h1>All Clients</h1><br>
    <%= link_to "Create New client", new_client_path%>
    <br><br><br>
    <% @clients.each do |client|%>
        <%= image_tag client.image, :class => "row g-3 col-lg-4" if client.image.present? %>
            <ul>
                <br>
                <li>Name: <%= link_to client.name, client %></li>
                <br>
            </ul>   
    <% end %>
</div>

app/views/clients/new.html.erb
<div class="container-sm">
    <h1>New Client</h1>

    <%= render :partial => 'form' %>
      
</div>

app/views/clients/show.html.erb
<div class="container">
    <h1><%= @client.name %></h1><br>
    <div class="row">
        <div class="col">
            <%= image_tag @client.image, :class => 'profileimg' if @client.image.present? %>
        </div>
        <div class="col">
            <ul class="list-group">
                <li class="list-group-item list-group-item-secondary">Name: <%= @client.name %></li>
                <li class="list-group-item list-group-item-success">phone: <%= @client.phone %></li>
                <li class="list-group-item list-group-item-secondary">email: <%= @client.email %></li>
                <li class="list-group-item list-group-item-success">Address: <%= @client.address %></li>
                <li class="list-group-item list-group-item-secondary">Heard us from: <%= @client.heard_us_from %></li>
                <li class="list-group-item list-group-item-success">preferred_style: <%= @client.preferred_style %></li>
                <li class="list-group-item list-group-item-secondary">Projects:  <% @client.projects.each do |project| %>
                    <%= link_to project.name, project %>
                    <% end %>
                </li>
            </ul>
            <br>

            <div class="controls">
                <%= link_to "Edit client", edit_client_path(@client), :class=>"btn btn-primary"%>
                <br><br>
                <%= button_to "Delete client", @client, :class=>"btn btn-danger", :method => 'delete', :data => { :confirm => "Are you sure?"} %>
            </div>
        </div>
    </div>
</div>

app/views/designers/_form.html.erb
<%= form_for @designer do |f| %>
    <%= f.label :name, :class=>'form-control-plaintext' %>
    <%= f.text_field :name, :class => 'form-control'%>
    <%= f.label :dob, 'Date of birth', :class=>'form-control-plaintext'%>
    <%= f.text_field :dob, :placeholder => 'YYYY-MM-DD', :class => 'form-control'%>
    <%= f.label :hireyear, 'Employment Date', :class=>'form-control-plaintext' %>
    <%= f.text_field :hireyear, :class => 'form-control' %>
    <%= f.label :email, :class=>'form-control-plaintext'%>
    <%= f.text_field :email, :class => 'form-control'%>
    <%= f.label :phone, :class=>'form-control-plaintext'%>
    <%= f.text_field :phone, :class => 'form-control'%>
    <%= f.label :address, :class=>'form-control-plaintext'%>
    <%= f.text_field :address, :class => 'form-control'%>
    <%= f.label :award, :class=>'form-control-plaintext' %>
    <%= f.text_field :award, :class => 'form-control' %>
    <%= f.label :image, :class=>'form-control-plaintext'%>
    <%= f.text_field :image, :class => 'form-control'%>
    <br>
    <%= f.submit%>
<% end %>

app/views/designers/edit.html.erb
<div class="container-sm">
    <h1>Edit Client</h1>

    <%= render :partial => 'form' %>
</div>

app/views/designers/index.html.erb
<div class="container">
    <h1>All Designers</h1><br>
    <%= link_to "Create New Designer", new_designer_path%>
    <br><br><br>
    <% @designers.each do |designer|%>
        <%= image_tag designer.image, :class=>"profileimg" if designer.image.present? %>
            <ul>
                <br>
                <li>Name: <%= link_to designer.name, designer %></li>
                <br>

            </ul>
    <% end %>
</div>

app/views/designers/new.html.erb
<div class="container-sm">
    <h1>New Designer</h1>

    <%= render :partial => 'form' %>
</div>

app/views/designers/show.html.erb
<div class="container">
    <h1><%= @designer.name %></h1><br>
    <div class="row">
        <div class="col">
            <%= image_tag @designer.image, :class => 'profileimg' if @designer.image.present? %>
        </div>
        <div class="col">
            <ul class="list-group">
                <li class="list-group-item list-group-item-secondary">Name: <%= @designer.name %></li>
                <li class="list-group-item list-group-item-success">Date of Birth: <%= @designer.dob.strftime '%B %e, %Y' %></li>
                <li class="list-group-item list-group-item-secondary">Emplyment Date: <%= @designer.hireyear %></li>
                <li class="list-group-item list-group-item-success">phone: <%= @designer.phone %></li>
                <li class="list-group-item list-group-item-secondary">email: <%= @designer.email %></li>
                <li class="list-group-item list-group-item-success">Address: <%= @designer.address %></li>
                <li class="list-group-item list-group-item-secondary">Award: <%= @designer.award %></li>
                <li class="list-group-item list-group-item-success">Projects:  <% @designer.projects.each do |project| %>
                    <%= link_to project.name, project %>
                    <% end %>
                </li>
            </ul>
            <br>

           
            <div class="controls">
                <%= link_to "Edit designer", edit_designer_path(@designer), :class=>"btn btn-primary"%>
                <br><br>
                <%= button_to "Delete designer", @designer, :class=>"btn btn-danger", :method => 'delete', :data => { :confirm => "Are you sure?"} %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Archdesign</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>@import url('https://fonts.googleapis.com/css2?family=Heebo&display=swap');</style>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-white" id="navibar">
      <div class="container-fluid">
      <a class="navbar-brand" href="#"><%= image_tag("logo/logo.jpg", width:"100px") %></a>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" >
        <li class="nav-item">
        <%= link_to 'Home', root_path, :class => "nav-link active"  %>
        </li>
        <li class="nav-item">
        <%= link_to "All Designers", designers_path, :class => "nav-link"%>
        </li>
        <li class="nav-item">
        <%= link_to "All clients", clients_path, :class => "nav-link"%>
        </li>
        <li class="nav-item">
        <%= link_to "All projects", projects_path, :class => "nav-link"%>
        <li>
      </ul>
      <ul class="navbar-nav justify-content-end">
        <% if @current_user.present?%>
          <% if @current_user.admin?%>
            <%= link_to "ALL users", users_path %>
          <% end %>
         
          <%= link_to "Sign out #{ @current_user.email}", login_path, :method => 'delete', :class => "nav-link"%>
        
        <% else %>
        <li class="nav-item">
        <%= link_to "Sign up",  new_user_path, :class => "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Sign in", login_path, :class => "nav-link"%>
        </li>
        <% end %>
        </ul>
        </div>
      </nav>
      
    </header>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="hero vh-100 d-flex align-items-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-7">
                <h1 class="display-5" id="slogan">Your dream design starts here</h1><br>
                <p id="homepage">Explore our magnificant projects <br> Meet our dedicated designers <br> And make your own dream come true</p> 
                <%= link_to "Explore", projects_path, :class => "btn btn-primary"%> 
            </div>
        </div>
    </div>
</div>
<div id="preview">
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto text-center">
            <h4 class="text-primary">Projects</h4>
            <h1>Our Recent Design</h1>
        </div>
    </div><br>
    <div class="row g-3">
        <div class="col-lg-4 col-sm-3">
            <div class="project">
                <img src="/assets/projects/project01/p1.jpeg" alt="">
                <div class= "overlay">
                    <h4 class="text-white">Coastal Retreat</h4>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-sm-3">
            <div class="project">
                <img src="/assets/projects/project02/p1.jpeg" alt="">
                <div class= "overlay">
                    <h4 class="text-white">Surfrider Ranch</h4>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-sm-3">
            <div class="project">
                <img src="/assets/projects/project03/p1.jpeg" alt="">
                <div class= "overlay">
                    <h4 class="text-white">Pixel</h4>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-sm-3">
            <div class="project">
                <img src="/assets/projects/project04/p2.jpeg" alt="">
                <div class= "overlay">
                    <h4 class="text-white">Open House</h4>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-sm-3">
            <div class="project">
                <img src="/assets/projects/project05/p1.jpeg" alt="">
                <div class= "overlay">
                    <h4 class="text-white">Westmount Residence</h4>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-sm-3">
            <div class="project">
                <img src="/assets/projects/project06/p1.jpeg" alt="">
                <div class= "overlay">
                    <h4 class="text-white">Forest Knoll</h4>
                </div>
            </div>
        </div>
    </div>
</div>

 <section id="designer">
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto text-center">
                <h4 class="text-primary">Designers</h4>
                <h1>Meet our designers</h1>
                
            </div>
        </div><br>
        <div class="row row-cols-1 row-cols-md-3 g-4" id="desginer_pics">
            <div class="col ">
                <div class="card text-center offset-md-1" style="width: 20rem;">
                    <img src="/assets/designers/d1.png" class="card-img-top" alt="">
                    <div class="card-body">
                        <h5 class="card-title">John Smith</h5>
                        <p class="card-text">Australia Good Design - 2009</p>
                    </div>
                    
                </div>
            </div>
            <div class="col ">
                <div class="card text-center offset-md-1" style="width: 20rem;">
                    <img src="/assets/designers/d3.webp" class="card-img-top" alt="">
                    <div class="card-body">
                        <h5 class="card-title">William Hugh</h5>
                        <p class="card-text">Best Portsea Designer - 2019</p>
                    </div>
                    
                </div>
            </div>
            <div class="col ">
                <div class="card text-center offset-md-1" style="width: 20rem;">
                    <img src="/assets/designers/d5.jpeg" class="card-img-top" alt="">
                    <div class="card-body">
                        <h5 class="card-title">Sally Grey</h5>
                        <p class="card-text">Prospect Young Designer - 2015</p>
                    </div>
                    
                </div>
            </div>
            
        </div>
    </div>
</section>

<section id="contact">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-8 mx-auto text-center">
                <h6 class="text-primary">CONTACT</h6>
                <h1>Get In Touch</h1>
            </div>
        </div>

        <form action="" class="row g-3 justify-content-center">
            <div class="col-md-4">
                <input type="text" class="form-control" placeholder="Full Name">
            </div>
            <div class="col-md-4">
                <input type="text" class="form-control" placeholder="Enter E-mail">
            </div>
            <div class="col-md-8">
                <input type="text" class="form-control" placeholder="Enter Subject">
            </div>
            <div class="col-md-8">
                <textarea name="" id="" cols="30" rows="5" class="form-control"
                    placeholder="Enter Message"></textarea>
            </div>
            <div class="col-md-8 d-grid">
                <button class="btn btn-primary">Contact</button>
            </div>
        </form>

    </div>
</section>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
    <%= f.label :name, :class=>'form-control-plaintext'%>
    <%= f.text_field :name, :class => 'form-control'%>
    <%= f.label :location%>
    <%= f.text_field :location, :class => 'form-control'%>
    <%= f.label :area%>
    <%= f.text_field :area, :class => 'form-control'%>
    <%= f.label :style%>
    <%= f.text_field :style, :class => 'form-control'%>
    <%= f.label :start_date, 'Start Date'%>
    <%= f.text_field :start_date, :placeholder => 'YYYY-MM-DD', :class => 'form-control'%>
    <%= f.label :estimate_time_finish, 'Estimate time of completion'%>
    <%= f.text_field :estimate_time_finish, :placeholder => 'YYYY-MM-DD', :class => 'form-control'%>
    <%= f.label :cost%>
    <%= f.text_field :cost, :class => 'form-control'%>
    <%= f.label :image%>
    <%= f.text_field :image, :class => 'form-control'%><br>
    <%= f.submit%>
<% end %>

app/views/projects/edit.html.erb
<div class="container-sm">
    <h1>Edit Projects</h1>

    <%= render :partial => 'form' %>
</div>

app/views/projects/index.html.erb
<div class="container">
    <h1>All Projects</h1><br>
    <%= link_to "Create New Project", new_project_path%>
    <br><br><br>
    <% @projects.each do |project|%>
    
        <%= image_tag project.image, :class => "row g-3 col-lg-4" if project.image.present? %>
            <ul>
                <br>
                <li>Name: <%= link_to project.name, project %></li>
                <br>
            </ul>
    
    <% end %>


</div>

app/views/projects/new.html.erb
<div class="container-sm">
    <h1>New Projects</h1>

    <%= render :partial => 'form' %>
</div>

app/views/projects/show.html.erb
<div class="container">
    <h1><%= @project.name %></h1><br>
    <div class="row">
        <div class="col">
            <%= image_tag @project.image, :class => 'feature' if @project.image.present? %>
        </div>
        <div class="col">
            <ul class="list-group">
                <li class="list-group-item list-group-item-secondary">Name: <%= @project.name %></li>
                <li class="list-group-item list-group-item-success">Location: <%= @project.location %></li>
                <li class="list-group-item list-group-item-secondary"> Area: <%= @project.area %> sqm</li>
                <% unless @project.start_date.nil? %>
                    <li class="list-group-item list-group-item-success">Start Date: <%= @project.start_date.strftime '%B %e, %Y' %></li>
                <% end %>
                <li class="list-group-item list-group-item-secondary">Style: <%= @project.style %></li>
                
                <li class="list-group-item list-group-item-success">Cost: <%= @project.cost %></li>
                <% unless @project.estimate_time_finish.nil? %>
                    <li class="list-group-item list-group-item-secondary">Estimate time of completion: <%= @project.estimate_time_finish.strftime '%B %e, %Y' %></li>
                <% end %>
            </ul>
            <br>
        
            <div class="controls">
                <%= link_to "Edit project", edit_project_path(@project), :class=>"btn btn-primary"%>
                <br><br>
                <%= button_to "Delete project", @project, :class=>"btn btn-danger", :method => 'delete', :data => { :confirm => "Are you sure?"} %>
            </div>
        </div>
    </div>
</div>

app/views/session/new.html.erb
<div class="container">
<h1>Log in</h1><br>

<%= form_tag login_path do %>
    <%= label_tag :email %>
    <%= email_field_tag :email%>
    <%= label_tag :password %>
    <%= password_field_tag :password%>
    <%= submit_tag "Sign in" %>
<% end %>
</div>

app/views/users/index.html.erb
<h1>All users</h1>

<% @users.each do |user| %>
    <p><%= user.email%></p>
<% end %>

app/views/users/new.html.erb
<div class="container">

<h1>Sign up</h1>

<% if @user.errors.any?%>
    <ol>
        <% @user.errors.full_messages.each do |msg|%>
            <li><%= msg %></li>
        <% end%>
    </ol>
<% end %>

<%= form_for @user do |f| %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    
    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Sign up" %>
<% end %>

</div>